-- TABEL MASTER PRODUK
CREATE TABLE IF NOT EXISTS master_produk (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_produk VARCHAR(100) NOT NULL,
    parameter_dinamis JSON,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TABEL QC RECORDS
CREATE TABLE IF NOT EXISTS qc_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_produk INT NOT NULL,
    tanggal DATE NOT NULL,
    shift VARCHAR(10) NOT NULL,
    grup VARCHAR(10) NOT NULL,
    mesin VARCHAR(10) NOT NULL,
    waktu VARCHAR(20) NOT NULL,
    parameter_dinamis JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_produk) REFERENCES master_produk(id) ON DELETE CASCADE
);

-- TABEL USERS
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nama_lengkap VARCHAR(100)
);